### ISSUE TITLE
Is dockerization a good idea for this template?

### ISSUE THREAD

**Issue by thiagoszbarros** [pestphp/pest-plugin-template#11]
Some months ago I used this template as base to create a package and now I added the dockerization feature to improve contributing experience. I can do the same for this template but I'm here to ask if is that a good idea or dockerize this template is not required?

**Comment by owenvoke** [comment]
Personally I don't think it adds a huge amount of value to here, and I think that people creating their own plugins should decide whether they want Docker support or not. 🤔 Then again, I don't do much in this repo, so it may be useful for some people.

**Comment by thiagoszbarros** [comment]
> Personally I don't think it adds a huge amount of value to here, and I think that people creating their own plugins should decide whether they want Docker support or not. 🤔 Then again, I don't do much in this repo, so it may be useful for some people.

Sure, mainly due this I asked before opening a pull request.
